apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: nhh0507/gateway-service:v1.0.0
          ports:
            - containerPort: 9004
          volumeMounts:
            - name: config-volume
              mountPath: /config/application.properties
              subPath: application.properties
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: gateway-config
