apiVersion: v1
kind: Service
metadata:
  name: gateway-service-svc
spec:
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9004
      nodePort: 30008  # Đây là NodePort
  type: NodePort
