version: '3.8'
## MYSQL config
services:
  mysql-microservice:
    image: mysql:8.0.33
    container_name: mysql-microservice
    ports:
      - "3306:3306"
    restart: always
    volumes:
       - /home/hoanghai/Mysql/mysql8.0.33:/var/lib/mysql
    networks:
      backend:
    environment:
      MYSQL_USER: hainh
      MYSQL_PASSWORD: Admin123
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_DATABASE: testdata

  ## REDIS config
  redis-container:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /home/hoanghai/Redis/redis-container:/data
    networks:
      backend:

#
#  ## discovery-service config
#  discovery-service:
#    image: nhh0507/discovery-service:v1.0.0
#    container_name: discovery-service
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    ports:
#      - "8761:8761"
#    networks:
#      backend:
#
### gateway-service config
#  gateway-service:
#    image: nhh0507/gateway-service:v1.0.0
#    container_name: gateway-service
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - eureka_client_service-url_defaultZone=http://discovery-service:8761/eureka
#    ports:
#      - "9004:9004"
#    networks:
#      backend:
#    depends_on:
#      - discovery-service
#
### identity-service config
#  identity-service:
#    image: nhh0507/identity-service:v1.0.0
#    container_name: identity-service
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - eureka_client_service-url_defaultZone=http://discovery-service:8761/eureka
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-microservice:3306/testdata
#    ports:
#      - "9006:9006"
#    networks:
#      backend:
#    depends_on:
#      - discovery-service
#      - gateway-service
#      - mysql-microservice
#
### identity-service config
#  inventory-service:
#    image: nhh0507/inventory-service:v1.0.0
#    container_name: inventory-service
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - eureka_client_service-url_defaultZone=http://discovery-service:8761/eureka
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-microservice:3306/testdata
#    ports:
#      - "9003:9003"
#    networks:
#      backend:
#    depends_on:
#      - discovery-service
#      - gateway-service
#      - mysql-microservice
#
### product-service config
#  product-service:
#    image: nhh0507/product-service:v1.0.0
#    container_name: product-service
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - eureka_client_service-url_defaultZone=http://discovery-service:8761/eureka
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-microservice:3306/testdata
#    ports:
#      - "9001:9001"
#    networks:
#      backend:
#    depends_on:
#      - discovery-service
#      - gateway-service
#      - mysql-microservice
#
### order-service config
#  order-service:
#    image: nhh0507/order-service:v1.0.0
#    container_name: order-service
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - eureka_client_service-url_defaultZone=http://discovery-service:8761/eureka
#      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-microservice:3306/testdata
#    ports:
#      - "9002:9002"
#    networks:
#      backend:
#    depends_on:
#      - discovery-service
#      - gateway-service
#      - mysql-microservice

## create network
networks:
  backend:
    name: springboot-app-network
