apiVersion: v1
kind: Service
metadata:
  name: identity-service-svc
spec:
  selector:
    app: identity-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9006
      nodePort: 30006  # Đây là NodePort
  type: NodePort
