apiVersion: v1
kind: Service
metadata:
  name: discovery-service-svc
spec:
  selector:
    app: discovery-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8761
      nodePort: 30007  # Đây là NodePort
  type: NodePort
