FROM openjdk:11
EXPOSE 8761
COPY target/spring-discovery-service-0.0.1-SNAPSHOT.jar spring-discovery-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/spring-discovery-service-0.0.1-SNAPSHOT.jar"]