version: '3.9'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "80:80" # Map port 80 trên host đến port 80 trong container
      - "443:443" # Map port 443 nếu cần HTTPS
    networks:
      - minikube

networks:
  minikube:
    name: minikube
    external: true
