apiVersion: v1
kind: ConfigMap
metadata:
  name: product-config
data:
  application.properties: |
    server.port=9001
    spring.application.name=product-service
    eureka.client.service-url.defaultZone =  http://192.168.49.2:30007/eureka
    spring.datasource.url=jdbc:mysql://192.168.49.6:3306/testdata
    spring.datasource.username=root
    spring.datasource.password=Admin123
    spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    spring.jpa.properties.hibernate.format_sql=true
    spring.jpa.show-sql = false
    spring.jpa.hibernate.ddl-auto = none
    spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
    spring.jpa.properties.hibernate.globally_quoted_identifiers=true
    # REDIS CONFIG
    redis.host=192.168.49.5
    redis.port=6379
    spring.zipkin.base-url=http://192.168.49.4:9411
    spring.sleuth.sampler.probability=1.0
    spring.main.allow-circular-references=true
