apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9002
      nodePort: 30002  # Đây là NodePort
  type: NodePort
