spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origins: 'http://10.56.66.60:3000'
            allowed-headers: '*'
            allowed-methods:
              - OPTIONS
              - GET
              - POST
              - PUT